global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ubuntu-server'
    static_configs:
      - targets: ['13.60.249.72:9100']

  - job_name: 'linux-host'
    static_configs:
      - targets: ['linux-host:9100']


